// <auto-generated />
namespace AdminApps.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class InstallProjectMgmtModuleV1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InstallProjectMgmtModuleV1));
        
        string IMigrationMetadata.Id
        {
            get { return "201509220117360_InstallProjectMgmtModuleV1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
