/*
@license

dhtmlxGantt v.3.3.0 Professional Evaluation
This software is covered by DHTMLX Evaluation License. Contact sales@dhtmlx.com to get Commercial or Enterprise license. Usage without proper license is prohibited.

(c) Dinamenta, UAB.
*/
Gantt.plugin(function(t){t.config.auto_scheduling=!1,t.config.auto_scheduling_initial=!0,t.config.auto_scheduling_strict=!1,t._datesNotEqual=function(t,e){return t.valueOf()>e.valueOf()?this._hasDuration(e,t):this._hasDuration(t,e)},t._firstSmaller=function(t,e){return t.valueOf()<e.valueOf()&&this._hasDuration(t,e)?!0:!1},t._firstBigger=function(t,e){return this._firstSmaller(e,t)},t._notEqualTaskDates=function(e,n){return this._datesNotEqual(e.start_date,n.start_date)||(this._datesNotEqual(e.end_date,n.end_date)||e.duration!=n.duration)&&e.type!=t.config.types.milestone?!0:void 0;
},t._autoScheduleHandler=function(e,n,i){if(t.config.auto_scheduling&&!this._autoscheduling_in_progress){var a=this.getTask(e);t._notEqualTaskDates(i,a)&&t.autoSchedule(a.id)}return!0},t._linkChangeAutoScheduleHandler=function(e,n){t.config.auto_scheduling&&!this._autoscheduling_in_progress&&t.autoSchedule(n.source)},t._autoScheduleOnLoadHandler=function(){t.config.auto_scheduling&&t.config.auto_scheduling_initial&&t.autoSchedule()},t._checkCircularDependency=function(e,n,i){if(i[e.id])return!1;i[e.id]=!0;
for(var a,s=0;s<e.$source.length;s++)if(e.$source[s]!=n.id){var r=this.getLink(e.$source[s]);if(a=this.getTask(r.target),!this._checkCircularDependency(a,n,i))return!1}if(e.id==n.source&&(a=this.getTask(n.target),!this._checkCircularDependency(a,n,i)))return!1;for(var o=t.getChildren(e.id),s=0;s<o.length;s++){var d=this.getTask(o[s]);if(0==d.$target.length&&!this._checkCircularDependency(d,n,i))return!1}return!0},t._checkParents=function(e,n){if(n[e])return!1;if(e!=t.config.root_id){var i=t.getParent(e);
if(i!=t.config.root_id)return t._checkParents(i,n)}return!0},t._linkValidationHandler=function(e,n){var i=!(t.isChildOf(n.target,n.source)||t.isChildOf(n.source,n.target))&&t._checkCircularDependency(t.getTask(n.source),n,{});return i||t.callEvent("onCircularLinkError",[n]),i},t._lightBoxChangesHandler=function(e,n){if(t.config.auto_scheduling&&!this._autoscheduling_in_progress){var i=this.getTask(e);t._notEqualTaskDates(n,i)&&(t._autoschedule_lightbox_id=e)}return!0},t._lightBoxSaveHandler=function(e,n){
return t.config.auto_scheduling&&!this._autoscheduling_in_progress&&t._autoschedule_lightbox_id&&t._autoschedule_lightbox_id==e&&(t._autoschedule_lightbox_id=null,t.autoSchedule(n.id)),!0},t.attachEvent("onAfterLinkUpdate",t._linkChangeAutoScheduleHandler),t.attachEvent("onAfterLinkAdd",t._linkChangeAutoScheduleHandler),t.attachEvent("onParse",t._autoScheduleOnLoadHandler),t.attachEvent("onBeforeLinkAdd",t._linkValidationHandler),t.attachEvent("onBeforeLinkUpdate",t._linkValidationHandler),t.attachEvent("onBeforeTaskChanged",t._autoScheduleHandler),
t.attachEvent("onLightboxSave",t._lightBoxChangesHandler),t.attachEvent("onAfterTaskUpdate",t._lightBoxSaveHandler),t.autoSchedule=function(e){if(t.callEvent("onBeforeAutoSchedule",[e])!==!1){var n,i={};if(e)n=this.getTask(e),i=t._autoScheduleByTask(n,i);else for(var a=t.getChildren(t.config.root_id),s=0;s<a.length;s++)n=this.getTask(a[s]),i=t._autoScheduleByTask(n,i);t._updateTasks(i);var r=[];for(var s in i)r.push(s);t.callEvent("onAfterAutoSchedule",[e,r])}},t._autoScheduleByTask=function(e,n){
return t.config.auto_scheduling_strict?n=t._autoScheduleLinkedTasks(e,n,null,e.id):(n=t._autoScheduleLinkedTasks(e,n,null),e.parent&&e.parent!=t.config.root_id&&(n=t._autoScheduleParents(this.getTask(e.parent),n))),n},t._autoScheduleLinkedTasks=function(e,n,i,a){var s;if(void 0===e.auto_scheduling||e.auto_scheduling){var r=t._getTaskMinimalStartDate(e);if(e.parent&&e.parent!=t.config.root_id){var o=this.getTask(e.parent),d=t._getProjectMinimalStartDate(o);r.date&&d.date?this._firstSmaller(r.date,d.date)&&(r=d):r.date||(r=d);
}var _=t._isTask(e)&&r.date&&(t.config.auto_scheduling_strict&&this._datesNotEqual(r.date,e.start_date)&&a!=e.id||this._firstBigger(r.date,e.start_date));if(_){if(t.callEvent("onBeforeTaskAutoSchedule",[e,r.date,r.link,r.source_task])===!1)return n;t._updateTaskPosition(e,r.date,e.duration),n[e.id]=!0}var l=this.getChildren(e.id),h=a&&t.isChildOf(a,e.id);if(l.length&&(!t.config.auto_scheduling_strict||!h||h&&_))for(s=0;s<l.length;s++)t._autoScheduleLinkedTasks(this.getTask(l[s]),n,i,a);_&&t.callEvent("onAfterTaskAutoSchedule",[e,r.date,r.link,r.source_task]);
}for(s=0;s<e.$source.length;s++){var c=this.getLink(e.$source[s]),g=this.getTask(c.target);t._autoScheduleLinkedTasks(g,n,i,a)}if(e.parent&&i&&e.parent!=t.config.root_id){var u=this.getTask(e.parent);t.config.auto_scheduling_strict?t._autoScheduleParents(u,n,a):t._autoScheduleParents(u,n)}return n},t._updateTaskPosition=function(t,e,n){t.start_date=this.getClosestWorkTime({date:e,dir:"future"}),t.end_date=this.calculateEndDate(e,n)},t._updateTasks=function(e){this._autoscheduling_in_progress=!0,t.batchUpdate(function(){
for(var n in e)t.updateTask(n)}),this._autoscheduling_in_progress=!1},t._calculateMinDate=function(t,e,n){var i=t.start_date,a=this.config.links;switch(n.type){case a.finish_to_start:i=e.end_date;break;case a.start_to_start:i=e.start_date;break;case a.start_to_finish:i=this.calculateEndDate(e.start_date,-1*(t.duration||1));break;case a.finish_to_finish:i=this.calculateEndDate(e.end_date,-1*t.duration)}return n.lag&&1*n.lag==n.lag&&(i=this.calculateEndDate(i,1*n.lag)),i},t._getTaskMinimalStartDate=function(e){
for(var n={},i=0;i<e.$target.length;i++){var a=this.getLink(e.$target[i]),s=this.getTask(a.source),r=e,o=s;t._isProject(e)&&(r=t.getSubtaskDates(e.id),r.duration=t.calculateDuration(r.start_date,r.end_date)),t._isProject(s)&&(o=t.getSubtaskDates(s.id),o.duration=t.calculateDuration(o.start_date,o.end_date));var d=t._calculateMinDate(r,o,a);(!n.date||this._firstSmaller(n.date,d))&&(n.date=new Date(d),n.link=a,n.source_task=s)}return n.date&&this._firstSmaller(e.start_date,n.date)&&(n._mustMove=!0),
n},t._getProjectMinimalStartDate=function(e){if(!e)return{};var n;n=t._isProject(e)?t._getTaskMinimalStartDate(e):{};var i;e.parent&&e.parent!=t.config.root_id&&(i=this.getTask(e.parent));var a=t._getProjectMinimalStartDate(i);return(!n.date||a.date&&this._firstSmaller(n.date,a.date))&&(n=a),n},t._autoScheduleParents=function(e,n,i){if(!e)return n;if(e.parent&&e.parent!=t.config.root_id){var a=this.getTask(e.parent);t._autoScheduleParents(a,n,i)}return t._autoScheduleLinkedTasks(e,n,0,i),n},t._isStrictParent=function(t,e){
if(!t)return!1;for(var n;this.getParent(n||t);)if(n=this.getParent(n||t),n==e)return!0;return!1},t._isTask=function(e){return!(e.type&&e.type==t.config.types.project||e.$no_start||e.$no_end)},t._isProject=function(t){return!this._isTask(t)}});
//# sourceMappingURL=../sources/ext/dhtmlxgantt_auto_scheduling.js.map